class ActionType {
  static GET_INSTALLATION_TYPE_DATA = 'GET_INSTALLATION_TYPE_DATA';
  static GET_INSTALLATION_TYPE_DATA_SUCCESS = 'GET_INSTALLATION_TYPE_DATA_SUCCESS';
  static GET_INSTALLATION_TYPE_DATA_FAILURE = 'GET_INSTALLATION_TYPE_DATA_FAILURE';


  static GET_INSTALLATION_CATEGORY_DATA = 'GET_INSTALLATION_CATEGORY_DATA';
  static GET_INSTALLATION_CATEGORY_DATA_SUCCESS = 'GET_INSTALLATION_CATEGORY_DATA_SUCCESS';
  static GET_INSTALLATION_CATEGORY_DATA_FAILURE = 'GET_INSTALLATION_CATEGORY_DATA_FAILURE';

  static GET_INSTALLATION_SUB_CATEGORY_DATA = 'GET_INSTALLATION_SUB_CATEGORY_DATA';
  static GET_INSTALLATION_SUB_CATEGORY_DATA_SUCCESS = 'GET_INSTALLATION_SUB_CATEGORY_DATA_SUCCESS';
  static GET_INSTALLATION_SUB_CATEGORY_DATA_FAILURE = 'GET_INSTALLATION_SUB_CATEGORY_DATA_FAILURE';

  static GET_INSTALLATION_BOUGHT_FROM_DATA = 'GET_INSTALLATION_BOUGHT_FROM_DATA';
  static GET_INSTALLATION_BOUGHT_FROM_DATA_SUCCESS = 'GET_INSTALLATION_BOUGHT_FROM_DATA_SUCCESS';
  static GET_INSTALLATION_BOUGHT_FROM_DATA_FAILURE = 'GET_INSTALLATION_BOUGHT_FROM_DATA_FAILURE';

  static GET_INSTALLATION_AREA_CITY_DATA = 'GET_INSTALLATION_AREA_CITY_DATA';
  static GET_INSTALLATION_AREA_CITY_DATA_SUCCESS = 'GET_INSTALLATION_AREA_CITY_DATA_SUCCESS';
  static GET_INSTALLATION_AREA_CITY_DATA_FAILURE = 'GET_INSTALLATION_AREA_CITY_DATA_FAILURE';

  static GET_INSTALLATION_HOME_TYPE_DATA = 'GET_INSTALLATION_HOME_TYPE_DATA';
  static GET_INSTALLATION_HOME_TYPE_DATA_SUCCESS = 'GET_INSTALLATION_HOME_TYPE_DATA_SUCCESS';
  static GET_INSTALLATION_HOME_TYPE_DATA_FAILURE = 'GET_INSTALLATION_HOME_TYPE_DATA_FAILURE';

  static GET_INSTALLATION_OUR_SERVICES_DATA = 'GET_INSTALLATION_OUR_SERVICES_DATA';
  static GET_INSTALLATION_OUR_SERVICES_DATA_SUCCESS = 'GET_INSTALLATION_OUR_SERVICES_DATA_SUCCESS';
  static GET_INSTALLATION_OUR_SERVICES_DATA_FAILURE = 'GET_INSTALLATION_OUR_SERVICES_DATA_FAILURE';

  static GET_INSTALLATION_TAMKEEN_POLICIES_DATA = 'GET_INSTALLATION_TAMKEEN_POLICIES_DATA';
  static GET_INSTALLATION_TAMKEEN_POLICIES_DATA_SUCCESS = 'GET_INSTALLATION_TAMKEEN_POLICIES_DATA_SUCCESS';
  static GET_INSTALLATION_TAMKEEN_POLICIES_DATA_FAILURE = 'GET_INSTALLATION_TAMKEEN_POLICIES_DATA_FAILURE';



}

export { ActionType }